/**
 * Simple Parable Explainer (MRP v1.0)
 *
 * Features:
 * - Fetches Bible text from BSB.json.
 * - Processes a predefined list of parables with multiple references and thorough explanations.
 * - Displays all references; allows clicking a reference to load its specific BSB text.
 * - Filters parables by title, explanation, or potentially text content (enhanced search).
 * - Remembers the last viewed parable using localStorage.
 * - Includes comprehensive error handling and user feedback.
 * - Focus on code clarity, comments, and testability suggestions.
 */
document.addEventListener('DOMContentLoaded', () => {

    // --- DOM Element References ---
    const listContainer = document.getElementById('parable-list');
    const textDisplay = document.getElementById('parable-text');
    const explanationDisplay = document.getElementById('parable-explanation');
    const referenceDisplay = document.getElementById('parable-reference');
    const searchInput = document.getElementById('search-input');
    const messageDisplay = document.getElementById('message-display');
    // Potential future element: const additionalContentDisplay = document.getElementById('additional-content');
  
    // --- State Variables ---
    let bsbData = null; // Holds the fetched BSB JSON data
    let parableIndex = []; // Holds processed: {id, title, allReferencesArray, explanation, searchableText}
    let currentlySelectedParableId = null; // ID (index) of the main parable being shown
    let currentlyDisplayedRef = null; // The specific reference string whose text is currently displayed
    let currentlySelectedListButton = null; // The button element selected in the list
  
    // --- Constants ---
    const LAST_VIEWED_STORAGE_KEY = 'parableExplainerLastViewedId_MRP'; // Use distinct key
  
    // --- Data Definitions ---
    // Target parables: Title, array of References, Thorough Explanation.
    // NOTE: Thorough explanations generated by AI based on previous prompt and approval.
    const targetParables = [
        // Matthew
        { title: "Salt of the Earth", references: ["Matthew 5:13"], explanation: "Jesus declares His followers are the 'salt of the earth,' essential for preserving goodness and adding spiritual 'flavor' to a corrupt world. This implies a distinct, counter-cultural lifestyle. However, He warns that if this distinctiveness ('saltiness') is lost through compromise or conformity, believers become ineffective ('good for nothing') in their Kingdom purpose. This calls for maintaining spiritual integrity and impactful witness, reflecting God's preserving and purifying grace in society." },
        { title: "Lamp Under a Bowl", references: ["Matthew 5:14-16", "Mark 4:21-22", "Luke 8:16", "Luke 11:33"], explanation: "Comparing believers to the 'light of the world' and a 'city on a hill,' Jesus emphasizes that their faith and good works, resulting from God's regenerative grace, are meant to be publicly visible, not hidden. Hiding this light (like putting a lamp under a basket) contradicts its purpose. Instead, it should shine openly to dispel darkness, reveal truth, and ultimately draw attention not to the believers themselves, but to glorify God the Father. It's a divine mandate for transparent Christian living and active witness in the world." },
        { title: "Wise and Foolish Builders", references: ["Matthew 7:24-27", "Luke 6:47-49"], explanation: "Concluding the Sermon on the Mount, Jesus contrasts two ultimate foundations for life. Hearing *and diligently acting* upon His authoritative teachings is likened to building a house on solid rock – a foundation secure enough to withstand life's inevitable storms (trials, temptations, final judgment). Conversely, merely hearing His words without heartfelt obedience is portrayed as building on unstable sand – seemingly easier initially, but leading to catastrophic collapse when tested. The parable powerfully underscores that true, saving discipleship involves not just intellectual agreement but a life actively submitted to the Lordship of Christ and His Word as the only secure basis for both present stability and eternal destiny." },
        { title: "New Cloth on an Old Coat", references: ["Matthew 9:16", "Mark 2:21", "Luke 5:36"], explanation: "Paired with the 'New Wine' parable, this illustrates the fundamental incompatibility of the new covenant reality brought by Christ with the old, worn-out structures of Mosaic law and tradition as practiced by the religious establishment. Attempting to merely 'patch' the old system (garment) with the vibrant truth of the Gospel (unshrunk cloth) is not only futile but damaging – the new, stronger element will inevitably tear away from the old, making the situation worse. It highlights the radical newness and discontinuity of the Kingdom age Jesus inaugurated, requiring a complete transformation, not just superficial repairs." },
        { title: "New Wine in Old Wineskins", references: ["Matthew 9:17", "Mark 2:22", "Luke 5:37-39"], explanation: "Complementing the 'New Cloth' illustration, Jesus compares the dynamic, expansive life of the Holy Spirit and the Gospel ('new wine') with its containers. This vibrant new reality requires 'new wineskins' – regenerated hearts, renewed minds, and flexible structures capable of holding the fermenting power of God's grace. Old, brittle wineskins (representing rigid legalism, tradition-bound hearts, or the limitations of the Old Covenant framework) cannot contain this new life; they will inevitably burst, resulting in the loss of both the container and the precious contents. It emphasizes the necessity of spiritual rebirth and yieldedness to receive and live out the fullness of Christ's kingdom." },
        { title: "The Sower", references: ["Matthew 13:3-9", "Mark 4:1-9", "Luke 8:4-8"], explanation: "Jesus uses the familiar image of a farmer scattering seed to illustrate the varied reception of the 'word of the kingdom'. The Sower is Christ (and His followers), the Seed is the Word of God, and the Soil represents different heart conditions. The Path (hardened heart) allows Satan to snatch the seed. Rocky Ground (superficial heart) receives gladly but lacks root for trials. Thorny Ground (worldly heart) allows cares and riches to choke the Word. Only Good Soil (receptive heart, prepared by God) hears, understands, and bears lasting fruit (in varying degrees). It stresses the importance of the hearer's disposition for the Word's effectiveness, highlighting both divine sovereignty in sowing and human responsibility in receiving. (Interpretation: Matt 13:18-23, Mark 4:13-20, Luke 8:11-15)." },
        { title: "The Weeds (Tares)", references: ["Matthew 13:24-30"], explanation: "The kingdom of heaven is likened to a field where good seed (children of the kingdom) is sown by the master (Jesus), but an enemy (Satan) secretly sows weeds (children of the evil one). The master wisely instructs servants not to uproot the weeds prematurely, lest they damage the wheat. Both must grow together until the harvest (end of the age), when angels will execute divine judgment, separating the wicked for fiery destruction and gathering the righteous into the Father's eternal kingdom. It explains the present, often perplexing, mixture of true believers and false professors within the visible church/world and assures of God's ultimate, perfect justice and separation. (Interpretation: Matt 13:36-43)." },
        { title: "The Mustard Seed", references: ["Matthew 13:31-32", "Mark 4:30-32", "Luke 13:18-19"], explanation: "Comparing the kingdom to a tiny mustard seed—proverbially small—Jesus highlights its apparently insignificant beginnings in His own ministry and early disciples. Yet, He prophesies its astonishing growth into a large plant or tree, providing shelter for 'birds of the air' (possibly representing nations or individuals finding refuge). It illustrates the surprising, extensive growth and eventual worldwide influence and visibility of God's kingdom from humble origins, defying worldly expectations of power." },
        { title: "The Leaven (Yeast)", references: ["Matthew 13:33", "Luke 13:20-21"], explanation: "Similar to the Mustard Seed's theme of growth from small beginnings, this parable emphasizes the *pervasive* and *internal* influence of the kingdom. Like a small amount of leaven inevitably working its way through a large quantity of dough until the whole batch is affected, the kingdom of heaven exerts a quiet, hidden, yet powerful and transformative influence from within individuals and society. It highlights the subtle, spreading, and ultimately total impact of God's reign." },
        { title: "The Hidden Treasure", references: ["Matthew 13:44"], explanation: "The kingdom of heaven is portrayed as a treasure of such immense, unexpected value that a man stumbling upon it in a field would hide it again, then joyfully liquidate all his assets to purchase the entire field, thereby securing the treasure. This vividly emphasizes the supreme, surpassing worth of discovering and entering God's kingdom (finding salvation in Christ). The joy of this discovery motivates radical sacrifice; all earthly possessions are counted loss compared to the value of gaining the kingdom." },
        { title: "The Pearl of Great Price", references: ["Matthew 13:45-46"], explanation: "Complementing the Hidden Treasure, this parable features a merchant *actively searching* for fine pearls. Upon finding one pearl of extraordinary, unique value (representing the kingdom or Christ), he recognizes its supreme worth and decisively sells everything else he owns to acquire it. This illustrates that recognizing the ultimate value of the kingdom motivates a focused, intentional, and complete commitment, where all else is willingly sacrificed to gain the pearl—Jesus Christ Himself and His salvation." },
        { title: "The Net (Drawing in the Net)", references: ["Matthew 13:47-50"], explanation: "The present operation of the kingdom is compared to a large dragnet cast into the sea, gathering fish of every kind, both good and bad. This represents the inclusive, indiscriminate initial reach of the gospel message in the world, drawing many into the sphere of its influence (the visible church). However, like fishermen sorting their catch on the shore, there will be a final reckoning at the 'end of the age'. Angels will separate the wicked from the righteous, casting the wicked into 'the fiery furnace', signifying eternal judgment. It underscores the current mixed state of the visible kingdom and the certainty of future divine separation based on true righteousness." },
        { title: "Owner of a House", references: ["Matthew 13:52"], explanation: "Jesus concludes this series of parables by asking if the disciples understood. Affirming their understanding, He compares every scribe (or teacher) 'trained for the kingdom of heaven' to the master of a household. Such a person skillfully brings out of his storeroom treasures both 'new and old'. This implies that a well-instructed disciple understands how the new truths of the kingdom taught by Jesus fulfill and relate to the established truths of the Old Testament Law and Prophets, and is able to dispense both appropriately." },
        { title: "The Lost Sheep", references: ["Matthew 18:12-14", "Luke 15:3-7"], explanation: "Illustrating God's tender heart for the individual and His seeking love, Jesus describes a shepherd possessing one hundred sheep who notices one has gone astray. He proactively leaves the ninety-nine in safety to diligently search for the single lost one. Upon finding it, his joy is immense, exceeding his joy over those who never strayed. Jesus applies this directly: It is not the Father's will that even one 'little one' (believer or potential believer) should perish, and there is great rejoicing in heaven over one sinner who repents. It highlights God's personal pursuit and the infinite value He places on each soul." },
        { title: "The Unforgiving Servant", references: ["Matthew 18:23-35"], explanation: "In response to Peter's question about the limits of forgiveness, Jesus tells of a king settling accounts. One servant owes an astronomical, unpayable debt (symbolizing our sin-debt before God), which the king mercifully cancels completely upon the servant's plea. However, this forgiven servant immediately finds a fellow servant who owes him a trivial amount and violently demands payment, refusing to show mercy. When the king learns of this hypocrisy, he rescinds the initial forgiveness and delivers the wicked servant to punishment until the original debt is paid. The stark lesson is that experiencing God's overwhelming grace and forgiveness absolutely obligates believers to forgive others from the heart; failure to do so demonstrates a fundamental misunderstanding or rejection of the grace received and incurs divine judgment." },
        { title: "The Workers in the Vineyard", references: ["Matthew 20:1-16"], explanation: "A landowner hires laborers for his vineyard at various hours throughout the day, agreeing to a standard daily wage (a denarius) with the first group. At the end of the day, he pays *all* workers the same full wage, starting with the last hired. Those hired first complain about the perceived unfairness. The landowner defends his right to be generous ('Are you envious because I am generous?') and reminds them they received what they agreed upon. This parable illustrates God's sovereign grace in salvation and rewards. Entrance into the kingdom and its blessings are based on God's generous call and gift, not strictly on human merit, timing, or duration of service. 'The last will be first, and the first will be last.'" },
        { title: "The Two Sons", references: ["Matthew 21:28-32"], explanation: "Jesus presents a scenario to the chief priests and elders: A father asks two sons to work in the vineyard. The first son initially refuses ('I will not') but later changes his mind and goes. The second son outwardly agrees ('I go, sir') but does not actually go. Jesus forces the leaders to admit the first son did the father's will. He then applies it directly: Tax collectors and prostitutes (who initially refused God but repented at John the Baptist's message) are entering the kingdom ahead of the religious leaders (who professed obedience but rejected both John and Jesus). It highlights that genuine repentance and actual obedience, not mere words or religious status, constitute doing God's will." },
        { title: "The Wicked Tenants", references: ["Matthew 21:33-44", "Mark 12:1-11", "Luke 20:9-18"], explanation: "Jesus tells of a landowner who established a vineyard (Israel) and leased it to tenants (Jewish religious leaders). He repeatedly sent servants (prophets) to collect his share of the fruit, but the tenants beat, killed, and stoned them. Finally, he sent his beloved son (Jesus), thinking they would respect him, but they killed the son as well, hoping to claim the inheritance. Jesus asks what the owner will do, leading to the conclusion that he will destroy those wicked tenants and lease the vineyard to others who will produce fruit. This is a clear allegory of Israel's leadership rejecting God's messengers and ultimately His Son, leading to their judgment and the transfer of kingdom privileges ('given to a people producing its fruits')." },
        { title: "The Wedding Feast", references: ["Matthew 22:1-14", "Luke 14:16-24"], explanation: "A king prepares a magnificent wedding feast for his son (representing God's invitation to the messianic kingdom celebration through Christ). The initially invited guests (Israel/leaders) make light of the invitation, offering lame excuses or even mistreating the king's messengers. Enraged, the king destroys the murderers and sends servants to gather anyone, good or bad, from the main roads (representing the inclusion of Gentiles/sinners through the gospel). However, the story adds a crucial element: the king notices a guest without a proper wedding garment (symbolizing the imputed righteousness of Christ received by faith). This unprepared guest is cast out into darkness. The parable shows God's generous but rejected invitation to Israel, the subsequent invitation to all people, and the necessity of genuine, faith-based righteousness (the 'garment') for final acceptance into the kingdom. 'For many are called, but few are chosen.'" },
        { title: "The Fig Tree", references: ["Matthew 24:32-35", "Mark 13:28-31", "Luke 21:29-33"], explanation: "Drawing a lesson from nature, Jesus points out that when a fig tree's branches become tender and sprout leaves, everyone recognizes that summer is near. In the same way, He teaches that when the specific signs He has just described concerning the Tribulation period begin to occur, His followers should know with certainty that His return ('He is near, right at the door') and the establishment of His kingdom are imminent. It's an encouragement to discern the 'signs of the times' and remain watchful, trusting the reliability of His prophetic word which will outlast heaven and earth." },
        { title: "The Faithful and Wise Servant", references: ["Matthew 24:45-51", "Luke 12:42-48"], explanation: "Jesus describes a master appointing a servant over his household to provide food rations while he is away. The 'faithful and wise' servant diligently performs his duties and is found doing so upon the master's unexpected return, receiving great reward and increased responsibility. Conversely, the 'wicked' servant assumes the master is delayed, begins to mistreat fellow servants, and indulges himself. He is caught unprepared by the master's sudden return and faces severe judgment ('cut him in pieces'). This parable urges readiness and faithful stewardship of responsibilities within the church/kingdom in light of Christ's certain but unscheduled return, warning against complacency, abuse of authority, and worldly indulgence." },
        { title: "The Ten Virgins", references: ["Matthew 25:1-13"], explanation: "The kingdom's arrival is compared to ten virgins awaiting a bridegroom. All have lamps, but only five ('wise') bring extra oil; the other five ('foolish') do not. The bridegroom is delayed, and all fall asleep. At the midnight cry announcing his arrival, the foolish realize their lamps are going out and ask the wise for oil, but are refused and told to buy their own. While they are gone, the bridegroom arrives, and only the five prepared virgins enter the wedding feast before the door is shut. The foolish are left outside, unrecognized by the bridegroom ('I do not know you'). The parable strongly emphasizes the need for genuine, personal, and persevering spiritual preparedness (oil often symbolizing the Holy Spirit or true saving faith) for the return of Christ, which may be delayed. Readiness cannot be borrowed or obtained at the last minute." },
        { title: "The Talents", references: ["Matthew 25:14-30", "Luke 19:11-27"], explanation: "Before a journey, a master entrusts talents (a large sum of money, representing God-given abilities, resources, opportunities, or stewardship) to three servants according to their abilities (five, two, and one). The first two servants trade and double their amounts, receiving praise ('Well done, good and faithful servant!') and greater responsibility upon the master's return. The third servant, out of fear of the master's perceived harshness, buries his talent and returns only the original amount. He is condemned as 'wicked and lazy,' has his talent taken away, and is cast into outer darkness. The parable teaches the principle of accountable stewardship: God expects believers to actively and faithfully use whatever gifts and opportunities He provides for the advancement of His kingdom. Fruitfulness is expected, and negligence stemming from fear or slothfulness results in severe judgment." },
        { title: "The Sheep and the Goats", references: ["Matthew 25:31-46"], explanation: "Jesus describes the scene of His glorious return and final judgment, where He, as King, will separate all nations 'as a shepherd separates the sheep from the goats.' The 'sheep' on His right inherit the kingdom prepared for them because, surprisingly to them, their acts of compassion towards fellow believers in need (feeding the hungry, clothing the naked, visiting the sick/imprisoned) were counted by Christ as service done directly 'to Me.' The 'goats' on His left are condemned to eternal punishment because they failed to perform these acts of mercy, thus demonstrating their lack of genuine relationship with Christ reflected in indifference to His suffering people ('you did not do it for Me'). It powerfully reveals that final judgment is based on the evidence of saving faith as manifested in practical love and service towards others, especially Christ's 'brothers and sisters'." },
        // Mark
        { title: "The Growing Seed", references: ["Mark 4:26-29"], explanation: "Unique to Mark's Gospel, Jesus compares the kingdom of God to a seed sown by a man who then goes about his life, sleeping and rising, while the seed independently sprouts and grows ('he knows not how'). The earth yields grain automatically through stages (stalk, head, full kernel). Only when ripe does the man harvest it. This emphasizes the mysterious, inherent, divine power residing within the proclaimed Word of the Kingdom to produce spiritual life and growth, often independent of human effort or full understanding. God brings about the growth and the final harvest (judgment/consummation) in His own timing and manner." },
        { title: "The Doorkeeper", references: ["Mark 13:33-37"], explanation: "Concluding His Olivet Discourse on the end times, Jesus compares the situation to a master leaving his house, assigning tasks to servants, and commanding the doorkeeper specifically to 'keep watch.' Because the master's return time is utterly unpredictable ('evening, or at midnight, or when the rooster crows, or in the morning'), the command is imperative: 'Watch!' This serves as a direct exhortation to all disciples throughout the church age to remain spiritually vigilant, alert, and actively engaged in their assigned duties, constantly prepared for the Lord's sudden return." },
        // Luke
        { title: "The Two Debtors", references: ["Luke 7:40-43"], explanation: "Responding to Simon the Pharisee's critical thoughts about the sinful woman anointing His feet, Jesus tells of a moneylender who cancelled the debts of two people—one owing ten times more than the other. He draws out Simon's agreement that the one forgiven the larger debt would consequently love the lender more. Jesus then contrasts Simon's lack of basic hospitality (no water, kiss, or oil) with the woman's extravagant display of repentant love and tears. Her actions demonstrated her deep gratitude stemming from the awareness of having been forgiven much (her many sins). It teaches that authentic love for Christ flows from a profound sense of release from the burden of sin through His forgiveness." },
        { title: "The Good Samaritan", references: ["Luke 10:25-37"], explanation: "An expert in the law, seeking to justify himself after correctly summarizing the law as loving God and neighbor, asks Jesus, 'And who is my neighbor?' Jesus replies with the story of a Jewish man robbed, beaten, and left half-dead. Both a priest and a Levite (religious figures) pass by without helping. However, a Samaritan (viewed with contempt by Jews) sees the man, is 'moved with pity,' compassionately tends his wounds, transports him to an inn, pays for his care, and promises to cover further expenses. Jesus forces the lawyer to identify the Samaritan as the one who *proved* to be a neighbor. The parable radically redefines neighborliness not by ethnicity, religion, or proximity, but by demonstrating active, sacrificial mercy to anyone found in need, thereby fulfilling the law's demand." },
        { title: "The Friend at Midnight", references: ["Luke 11:5-13"], explanation: "Following His teaching on prayer (the Lord's Prayer), Jesus uses an analogy to encourage persistence. He describes a man persistently knocking at a friend's door late at night, shamelessly requesting bread for an unexpected visitor. Though the friend initially refuses due to the inconvenience, he eventually gives in purely because of the requester's sheer persistence ('importunity' or 'shameless audacity'). Jesus then pivots: If even a reluctant human friend yields to persistent asking, how much more will our loving Heavenly Father respond generously ('give good gifts,' specifically the Holy Spirit in Luke's account) to His children who persistently ask, seek, and knock in prayer? It's an encouragement to pray boldly and without ceasing, trusting God's fatherly goodness." },
        { title: "The Rich Fool", references: ["Luke 12:13-21"], explanation: "After refusing to mediate an inheritance dispute and warning against greed, Jesus illustrates with a parable about a rich man whose land produced an overwhelming harvest. His response was self-focused: build bigger barns to store it all so he could 'take life easy; eat, drink and be merry.' But God intervenes, calling him a 'fool' because his life would be demanded that very night, rendering his accumulated wealth useless to him. Jesus concludes, 'This is how it will be with whoever stores up things for themselves but is not rich toward God.' It starkly warns against materialism and finding security in earthly possessions, urging instead the pursuit of spiritual wealth and a right relationship with God, which have eternal value." },
        { title: "The Unfruitful Fig Tree", references: ["Luke 13:6-9"], explanation: "A man had a fig tree planted in his vineyard that produced no fruit for three years. He instructed the vinedresser to cut it down as it was uselessly occupying ground. The vinedresser interceded, asking for one more year to fertilize and cultivate it, promising to cut it down if it still remained barren afterward. This parable illustrates God's judgment against persistent spiritual unfruitfulness (initially directed at Israel, but applicable broadly). It highlights God's patience and His provision of opportunities for repentance (represented by the vinedresser's care, perhaps signifying Christ's ministry or the Spirit's work), but also warns that His patience is not infinite; continued unresponsiveness ultimately leads to judgment." },
        { title: "The Lowest Seat at the Feast", references: ["Luke 14:7-14"], explanation: "Noticing how guests at a dinner chose places of honor, Jesus taught about humility. He advised choosing the lowest place, so the host might honor you by inviting you higher, thus avoiding the potential shame of being asked to move down. This illustrates a kingdom principle: 'For all those who exalt themselves will be humbled, and those who humble themselves will be exalted.' He extends the lesson to hospitality, urging hosts to invite the poor and disabled who cannot reciprocate, promising a greater reward from God 'at the resurrection of the righteous.'" },
        { title: "Counting the Cost", references: ["Luke 14:28-33"], explanation: "Addressing large crowds following Him, Jesus emphasizes the demanding nature of true discipleship using two analogies. First, a person building a tower must first calculate the cost to ensure completion, avoiding public ridicule for starting something they cannot finish. Second, a king going to war must first assess if his army is strong enough to face the enemy, seeking peace terms if not. Similarly, Jesus declares, prospective disciples must realistically consider the total commitment involved – prioritizing Him above family, self, and all possessions ('must give up everything'). Failure to 'count the cost' leads to an incomplete or abandoned discipleship journey." },
        { title: "The Lost Coin", references: ["Luke 15:8-10"], explanation: "Presented alongside the Lost Sheep, this brief parable describes a woman possessing ten silver coins who loses one. She diligently lights a lamp, sweeps her entire house, and searches carefully until she finds it. Upon finding the single lost coin, she calls her friends and neighbors together, exclaiming, 'Rejoice with me; I have found my lost coin!' Jesus draws the parallel: 'In the same way, I tell you, there is rejoicing in the presence of the angels of God over one sinner who repents.' It emphasizes the immense value God places on each individual soul and the meticulous, searching effort He extends, culminating in great heavenly joy upon their recovery through repentance." },
        { title: "The Prodigal Son", references: ["Luke 15:11-32"], explanation: "This beloved parable dramatically illustrates God's redemptive heart. The younger son demands his inheritance early, travels far, squanders it in 'wild living,' and ends up feeding pigs in famine. Hitting rock bottom ('came to his senses'), he plans a repentant return, hoping only for servant status. However, his father sees him approaching, runs to him with compassion, embraces him, and orders a lavish celebration ('this son of mine was dead and is alive again!'). The dutiful older son resents this extravagant grace towards his repentant brother. The story showcases the depths of human sin and its consequences, the possibility of genuine repentance, the Father's overwhelming, unconditional love and forgiveness eagerly awaiting the returning sinner, and contrasts this with the cold self-righteousness that fails to understand or rejoice in such grace." },
        { title: "The Shrewd Manager", references: ["Luke 16:1-13"], explanation: "A manager accused of wasting assets, facing dismissal, cleverly uses his final moments of authority to reduce the amounts owed to his master by various debtors, thereby ingratiating himself with them for future assistance. Jesus surprisingly commends the dishonest manager *not* for his dishonesty, but for his *shrewdness* in using present resources to secure his future. He urges His disciples ('sons of light') to be equally astute in using worldly wealth ('unrighteous mammon') for eternal benefit – specifically, using resources generously to build relationships and gain heavenly rewards ('welcome you into eternal dwellings'). He concludes with principles on faithfulness in small things leading to faithfulness in larger trusts, and the impossibility of serving both God and Money." },
        { title: "The Rich Man and Lazarus", references: ["Luke 16:19-31"], explanation: "Jesus contrasts the earthly lives and immediate afterlives of an unnamed rich man (clothed in luxury, feasting daily) and a destitute beggar named Lazarus (covered in sores, longing for scraps, ignored by the rich man). After death, Lazarus is carried by angels to 'Abraham's side' (comfort), while the rich man finds himself in Hades in torment ('in agony in this fire'). A great, impassable chasm separates them. The rich man's pleas for mercy for himself and a warning for his living brothers are denied. Abraham states his brothers have the testimony of 'Moses and the Prophets' (Scripture); if they disregard God's written Word, even a messenger rising from the dead wouldn't convince them. The story serves as a stark warning against materialistic self-indulgence coupled with callous disregard for the poor, affirming the reality and finality of the afterlife and pointing to the sufficiency of Scripture for salvation." },
        { title: "Master and His Servant", references: ["Luke 17:7-10"], explanation: "Jesus poses a rhetorical question: Would a master, whose servant comes in from working the fields, immediately invite the servant to eat? No, the master would expect the servant to prepare *his* meal first and serve him, only eating afterward. The master wouldn't typically thank the servant for merely performing his required duties. Applying this, Jesus instructs His disciples: 'So you also, when you have done everything you were told to do, should say, «We are unworthy servants; we have only done our duty.»' This parable teaches an attitude of humble service towards God. Our obedience and service, even when complete, do not indebt God to us or merit special praise; they are simply our expected duty as His servants." },
        { title: "The Persistent Widow", references: ["Luke 18:1-8"], explanation: "To encourage His disciples 'always to pray and not give up,' Jesus tells of a persistent widow repeatedly appealing to an unjust judge (who neither feared God nor cared about people) for legal protection against her adversary. Though initially dismissive, the judge eventually relents, reasoning, 'Even though I don't fear God or care about anyone, yet because this widow keeps bothering me, I will see that she gets justice, so that she won't eventually come and attack me!' Jesus then argues from the lesser to the greater: If even an unrighteous judge yields to persistence, 'will not God bring about justice for his chosen ones, who cry out to him day and night? Will he keep putting them off? I tell you, he will see that they get justice, and quickly.' It's a powerful call to persistent, faith-filled prayer, trusting in God's justice and timing, even amidst delays." },
        { title: "The Pharisee and the Tax Collector", references: ["Luke 18:9-14"], explanation: "Addressing those 'confident of their own righteousness' who 'looked down on everyone else,' Jesus contrasts two men praying in the temple. The Pharisee stands prominently, thanking God he is not like other sinners (extortioners, adulterers, or the tax collector present) and lists his religious observances (fasting twice a week, tithing everything). In contrast, the tax collector stands at a distance, avoids even looking up to heaven, beats his breast in remorse, and prays simply, 'God, have mercy on me, a sinner.' Jesus declares it was the tax collector, not the Pharisee, who 'went home justified before God.' He concludes: 'For all those who exalt themselves will be humbled, and those who humble themselves will be exalted.' It starkly illustrates that justification comes not through self-righteous comparison or religious performance, but through humble recognition of one's sinfulness and complete reliance on God's mercy." },
        // John (Allegory/Discourse)
        { title: "The Shepherd and His Flock", references: ["John 10:1-18"], explanation: "While more of an extended metaphor or allegory than a narrative parable, Jesus uses shepherding imagery familiar to His audience. He contrasts Himself, the true 'gate' and 'Good Shepherd,' with 'thieves and robbers' (false religious leaders/messiahs) who try to enter improperly or harm the sheep. Jesus emphasizes His intimate relationship with His sheep (followers): He calls them by name, they know His voice and follow Him, He leads them to pasture (spiritual nourishment and life), and He grants them eternal life and security from which no one can snatch them. Critically, He distinguishes Himself from a mere 'hired hand' by stating He voluntarily 'lays down His life for the sheep,' signifying His substitutionary death and sacrificial love. He also speaks of 'other sheep' (Gentiles) He must bring into the one flock." }
      ];
  
    // --- Utility Functions ---
  
    /**
     * Parses a Bible reference string into an object. (Robust Implementation)
     * @param {string} refString - The Bible reference string.
     * @returns {object|null} Parsed object { book, chapter, startVerse, endVerse } or null on failure.
     */
    function parseRef(refString) {
      if (!refString || typeof refString !== 'string') return null;
      const match = refString.match(/^(.+?)\s+(\d+)\s*:\s*(\d+)(?:\s*-\s*(\d+))?\s*$/);
      if (!match) {
        console.error(`[parseRef] Failed: "${refString}"`);
        return null;
      }
      try {
        let bookName = match[1].trim();
        if (bookName === "Revelation of John") bookName = "Revelation";
        const chapter = parseInt(match[2], 10);
        const startVerse = parseInt(match[3], 10);
        const endVerse = match[4] ? parseInt(match[4], 10) : startVerse;
        if (isNaN(chapter) || isNaN(startVerse) || isNaN(endVerse) || chapter <= 0 || startVerse <= 0 || endVerse < startVerse) {
          console.error(`[parseRef] Invalid numbers: "${refString}"`);
          return null;
        }
        return { book: bookName, chapter, startVerse, endVerse };
      } catch (error) {
        console.error(`[parseRef] Error: "${refString}"`, error);
        return null;
      }
    }
  
    /**
     * Extracts text for a given parsed reference from the loaded BSB JSON data. (Robust Implementation)
     * @param {object} parsedRef - The object returned by parseRef.
     * @param {object} fullBsbData - The parsed BSB.json data.
     * @returns {string} The extracted Bible text, or a specific error indicator string.
     */
    function getTextFromBSB(parsedRef, fullBsbData) {
      const errorPrefix = "[Text Unavailable] ";
      if (!parsedRef) return errorPrefix + "Invalid reference format.";
      if (!fullBsbData || !Array.isArray(fullBsbData.books)) return errorPrefix + "BSB data missing/invalid.";
      const bookData = fullBsbData.books.find(b => b.name.toLowerCase() === parsedRef.book.toLowerCase());
      if (!bookData) return errorPrefix + `Book "${parsedRef.book}" not found.`;
      if (!Array.isArray(bookData.chapters)) return errorPrefix + `Invalid chapter data for "${parsedRef.book}".`;
      const chapterData = bookData.chapters.find(c => c.chapter === parsedRef.chapter);
      if (!chapterData) return errorPrefix + `Chapter ${parsedRef.chapter} not found in "${parsedRef.book}".`;
      if (!Array.isArray(chapterData.verses)) return errorPrefix + `Invalid verse data for ${parsedRef.book} ${parsedRef.chapter}.`;
      let extractedText = "";
      let versesFound = 0;
      for (let v = parsedRef.startVerse; v <= parsedRef.endVerse; v++) {
        const verseData = chapterData.verses.find(verse => verse.verse === v);
        if (verseData && typeof verseData.text === 'string') {
          extractedText += verseData.text.trim() + " ";
          versesFound++;
        } else {
          console.warn(`[getTextFromBSB] Verse ${v} missing/invalid in ${parsedRef.book} ${parsedRef.chapter}.`);
        }
      }
      if (versesFound === 0) return errorPrefix + `No verses found for range ${parsedRef.startVerse}-${parsedRef.endVerse} in ${parsedRef.book} ${parsedRef.chapter}.`;
      return extractedText.trim();
    }
  
    /**
     * Processes target parables to build the index used by the app.
     * Note: Text extraction happens dynamically on display in this version.
     */
    function processParables() {
      // Build index from targetParables; text is fetched on demand later.
      parableIndex = targetParables.map((target, index) => ({
        id: index,
        title: target.title,
        allReferencesArray: Array.isArray(target.references) ? target.references : [target.reference || "N/A"],
        explanation: target.explanation || "[Explanation not provided]"
      }));
  
      console.log(`[processParables] Initialized parable index with ${parableIndex.length} entries.`);
  
      // Render list and display initial parable (saved or default)
      if (parableIndex.length > 0) {
          renderList(parableIndex);
          const lastViewedId = loadLastParable();
          const initialParable = parableIndex.find(p => p.id === lastViewedId) || parableIndex[0];
          if (initialParable) displayParable(initialParable.id);
          showMessage(""); // Clear loading message
      } else {
          showMessage("Error: No parables could be processed.", "error");
          renderList([]);
      }
    }
  
    // --- UI Update Functions ---
  
     /**
     * Displays status messages (loading, error, info).
     * @param {string} message - The message text.
     * @param {string} type - 'loading', 'error', or 'info'.
     */
     function showMessage(message, type = 'info') {
        // Implementation remains the same - updates messageDisplay element
        messageDisplay.textContent = message;
        messageDisplay.className = message ? type : '';
        messageDisplay.style.display = message ? 'block' : 'none';
     }
  
    /**
     * Renders the list of parable buttons.
     * @param {Array} parablesToRender - Array of parable objects.
     */
    function renderList(parablesToRender) {
      // Implementation remains the same - clears and populates listContainer
      listContainer.innerHTML = '';
      if (!Array.isArray(parablesToRender) || parablesToRender.length === 0) {
        const message = searchInput.value.trim() ? 'No matching parables found.' : 'Parable list empty/error.';
        listContainer.innerHTML = `<p>${message}</p>`;
        return;
      }
      parablesToRender.forEach(parable => {
        const button = document.createElement('button');
        button.textContent = parable.title;
        button.setAttribute('data-id', parable.id);
        button.setAttribute('title', parable.allReferencesArray.join(', '));
        button.addEventListener('click', () => displayParable(parable.id));
        listContainer.appendChild(button);
      });
    }
  
    /**
     * Displays selected parable details (explanation, clickable refs) and loads primary text. Saves state.
     * @param {number} parableId - The ID of the parable in parableIndex.
     */
    function displayParable(parableId) {
      const selectedParable = parableIndex.find(p => p.id === parableId);
      if (!selectedParable) {
          console.error(`[displayParable] Parable ID ${parableId} not found.`);
          showMessage(`Error: Could not display details.`, 'error');
          return;
      }
  
      currentlySelectedParableId = parableId;
      saveLastParable(parableId);
  
      // Display Thorough Explanation
      explanationDisplay.innerHTML = `<h3>Explanation</h3><p>${selectedParable.explanation.replace(/\n/g, '<br>')}</p>`;
  
      // Render Clickable References
      let referenceHTML = '<p class="ref-label">References:</p>';
      if (selectedParable.allReferencesArray && selectedParable.allReferencesArray.length > 0) {
          selectedParable.allReferencesArray.forEach(ref => {
              referenceHTML += `<button class="ref-link" data-ref="${ref}">${ref}</button>`; // Store ref string
          });
      } else {
          referenceHTML += '<p>N/A</p>';
      }
      referenceDisplay.innerHTML = referenceHTML;
      // Add listeners AFTER rendering references
      referenceDisplay.querySelectorAll('.ref-link').forEach(link => {
          link.addEventListener('click', handleReferenceClick);
      });
  
      // Determine and display the primary reference text initially
      const primaryRefString = selectedParable.allReferencesArray[0] || null;
      if (primaryRefString) {
        displayTextForReference(primaryRefString, true, selectedParable.title); // Pass title for initial display
      } else {
        // Handle case where even primary reference is missing
        textDisplay.innerHTML = `<h2>${selectedParable.title}</h2><p>[Text Unavailable: No reference defined]</p>`;
        currentlyDisplayedRef = null; // Reset displayed ref state
        referenceDisplay.querySelectorAll('.ref-link').forEach(link => link.classList.remove('active')); // Ensure no ref is marked active
      }
  
      // Handle List Button Highlighting
      const selectedButton = listContainer.querySelector(`button[data-id='${parableId}']`);
      if (currentlySelectedListButton) currentlySelectedListButton.classList.remove('selected');
      if (selectedButton) {
          selectedButton.classList.add('selected');
          currentlySelectedListButton = selectedButton;
      }
      showMessage(""); // Clear messages on successful display
    }
  
     /**
     * Handles clicks on the dynamically generated reference links/buttons.
     * @param {Event} event - The click event object.
     */
     function handleReferenceClick(event) {
         event.preventDefault();
         const refString = event.target.getAttribute('data-ref');
         if (refString && refString !== currentlyDisplayedRef) { // Only update if different ref clicked
             displayTextForReference(refString, false); // False indicates not the primary text load
         } else if (!refString) {
             console.error("[handleReferenceClick] Clicked reference element missing data-ref attribute.");
         }
     }
  
    /**
     * Parses ref, gets BSB text, updates text display area, and highlights active ref link.
     * @param {string} refString - The reference string to display text for.
     * @param {boolean} isPrimary - Indicates if this is the initial text load for the main parable title.
     * @param {string} [title] - Optional: The title to display (used only if isPrimary).
     */
    function displayTextForReference(refString, isPrimary, title = null) {
        if (!bsbData) { // Ensure BSB data is loaded before trying to get text
            showMessage("Error: Bible data not loaded.", "error");
            textDisplay.innerHTML = `<h2>${title || 'Parable Text'}</h2><p>[Bible data unavailable]</p>`;
            return;
        }
  
        const parsedRef = parseRef(refString);
        const text = getTextFromBSB(parsedRef, bsbData); // Get text or error string
  
        // Update text display area. Use provided title only if it's the primary load.
        const currentTitle = isPrimary ? title : textDisplay.querySelector('h2')?.textContent || 'Parable Text';
        textDisplay.innerHTML = `<h2>${currentTitle}</h2><p>${text.replace(/\n/g, '<br>')}</p>`;
        currentlyDisplayedRef = refString; // Update state tracking displayed reference
  
        // Update highlighting on reference links/buttons
        referenceDisplay.querySelectorAll('.ref-link').forEach(link => {
            if (link.getAttribute('data-ref') === refString) {
                link.classList.add('active');
            } else {
                link.classList.remove('active');
            }
        });
    }
  
    // --- Filtering Function ---
  
    /**
     * Filters the parableIndex based on search input (title, explanation, maybe text).
     * Triggers re-rendering of the list. Enhanced for MRP.
     */
    function filterParables() {
      const searchTerm = searchInput.value.toLowerCase().trim();
      if (!Array.isArray(parableIndex)) return;
  
      // Enhanced search: Check title AND explanation
      const filteredParables = parableIndex.filter(parable =>
        parable.title.toLowerCase().includes(searchTerm) ||
        parable.explanation.toLowerCase().includes(searchTerm)
        // Future Enhancement: Could add pre-processed/indexed text search here if needed
      );
      renderList(filteredParables);
    }
  
    // --- State Persistence Functions ---
  
    /**
     * Saves the ID of the last selected parable title to localStorage.
     * @param {number} parableId - The ID to save.
     */
    function saveLastParable(parableId) {
        if (typeof(Storage) !== "undefined") {
            try {
                localStorage.setItem(LAST_VIEWED_STORAGE_KEY, parableId.toString());
            } catch (error) {
                console.warn("[saveLastParable] Error saving to localStorage:", error);
            }
        } else {
            console.warn("[saveLastParable] localStorage not supported.");
        }
    }
  
    /**
     * Loads the ID of the last selected parable title from localStorage.
     * @returns {number | null} The loaded ID or null.
     */
    function loadLastParable() {
         if (typeof(Storage) !== "undefined") {
             try {
                 const savedId = localStorage.getItem(LAST_VIEWED_STORAGE_KEY);
                 if (savedId !== null) {
                     const parsedId = parseInt(savedId, 10);
                     if (!isNaN(parsedId) && parsedId >= 0) return parsedId;
                 }
             } catch (error) {
                 console.warn("[loadLastParable] Error loading from localStorage:", error);
             }
         } else {
            console.warn("[loadLastParable] localStorage not supported.");
         }
        return null;
    }
  
  
    // --- Data Fetching and Initialization ---
  
    /**
     * Fetches BSB JSON, loads last state, triggers processing, handles errors robustly.
     */
    async function fetchDataAndInitialize() {
      showMessage("Loading Bible data...", "loading");
      listContainer.innerHTML = '<p>Loading...</p>';
      textDisplay.innerHTML = '<h2>Parable Text</h2><p>Loading data...</p>';
      explanationDisplay.innerHTML = '<h3>Explanation</h3>';
      referenceDisplay.innerHTML = '<p>References:</p>';
  
      const lastViewedId = loadLastParable();
  
      try {
        const response = await fetch('BSB.json');
        if (!response.ok) throw new Error(`HTTP error! Status: ${response.status} ${response.statusText}`);
        bsbData = await response.json();
  
        showMessage("Processing parables...", "loading");
        setTimeout(() => {
            processParables(); // Builds index, renders list, displays initial parable (using lastViewedId if available)
        }, 10);
  
      } catch (error) {
        console.error('Critical Error: Could not fetch or parse BSB.json:', error);
        showMessage(`Error: ${error.message}. Ensure BSB.json is valid and accessible.`, 'error');
        listContainer.innerHTML = '<p>Error loading data.</p>';
        textDisplay.innerHTML = '<h2>Error</h2><p>Could not load data.</p>';
      }
    }
  
    // --- Event Listeners Setup ---
    searchInput.addEventListener('input', filterParables);
    // Dynamic listeners added in renderList and displayParable
  
    // --- Initialisation ---
    fetchDataAndInitialize();
  
  }); // End of DOMContentLoaded listener